theme = "solarized_light"

[editor]
auto-format = true
bufferline = "always"
line-number = "relative"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
